
# demo

CREATE DATABASE IF NOT EXISTS blog_platform CHARACTER set utf8mb4;

USE blog_platform;

SHOW VARIABLES LIKE 'CHARACTER_SET_DATABASE';
SHOW VARIABLES LIKE 'COLLATION_DATABASE';

ALTER DATABASE blog_platform COLLATE 'utf8mb4_0900_as_cs';

DROP DATABASE IF EXISTS blog_platform;

SHOW DATABASES;